# Generated by Django 3.1.2 on 2021-04-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
