# Generated by Django 3.1.2 on 2021-04-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
